#!/usr/bin/env python3
"""Acceptance checks for the installable standalone skill layout."""

import re
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SKILL = ROOT / "skills" / "superarmanda"
EXPECTED_FILES = {
    "SKILL.md",
    "LICENSE",
    "references/profiles.md",
    "references/workflow.md",
    "references/review-contract.md",
    "references/pr-review.md",
    "references/waves.md",
    "references/role-briefs.md",
    "schemas/review-result.schema.json",
    "scripts/state.py",
    "scripts/review.py",
    "scripts/codex_review.py",
    "scripts/pr_review.py",
    "scripts/install-skill.py",
    "scripts/waves/wab.py",
    "scripts/waves/dash.py",
    "scripts/waves/gate.py",
    "scripts/waves/PROTOCOL.md",
    "scripts/waves/wab-open",
}


def source_files(skill):
    """List source files, excluding only CPython's generated bytecode cache."""
    files = set()
    for path in skill.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(skill)
        if relative.parent.name == "__pycache__" and path.suffix == ".pyc":
            continue
        files.add(relative.as_posix())
    return files


def assert_package_layout(skill):
    if source_files(skill) != EXPECTED_FILES:
        raise AssertionError(source_files(skill) ^ EXPECTED_FILES)


class StandaloneLayoutTest(unittest.TestCase):
    def test_skill_is_installable_from_the_canonical_skill_directory(self):
        assert_package_layout(SKILL)

    def test_rejects_missing_or_extra_source_files_but_allows_generated_bytecode(self):
        with tempfile.TemporaryDirectory() as directory:
            skill = Path(directory)
            for relative in EXPECTED_FILES:
                path = skill / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                path.touch()
            (skill / "scripts/__pycache__").mkdir()
            (skill / "scripts/__pycache__/state.cpython-312.pyc").touch()
            assert_package_layout(skill)

            (skill / "scripts/unexpected.py").touch()
            with self.assertRaises(AssertionError):
                assert_package_layout(skill)
            (skill / "scripts/unexpected.py").unlink()

            (skill / "scripts/state.py").unlink()
            with self.assertRaises(AssertionError):
                assert_package_layout(skill)

    def test_packaged_license_matches_repository_license(self):
        self.assertEqual(
            (ROOT / "LICENSE").read_text(encoding="utf-8"),
            (SKILL / "LICENSE").read_text(encoding="utf-8"),
        )


def flat(text):
    """Text with every whitespace run folded into one space: a rule may wrap across lines."""
    return " ".join(text.split())


def doc(relative):
    return (SKILL / relative).read_text(encoding="utf-8")


def fenced_blocks(text):
    return re.findall(r"```[^\n]*\n(.*?)```", text, flags=re.S)


class ReleasePolicyDocs(unittest.TestCase):
    """1.2.1 (#86): the model of a role follows the risk, a high-risk task needs two reviews."""

    RULE = "задачи про безопасность и маскировку обязаны иметь `risk: high`"

    def test_release_1_2_1_names_the_compatibility_boundary(self):
        changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
        sections = re.split(r"(?m)^## ", changelog)
        section = next((s for s in sections if s.startswith("1.2.1 — 2026-10-05")), None)
        self.assertIsNotNone(section, "CHANGELOG has no section 1.2.1")
        self.assertIn("#86", section)
        boundary = next((l for l in flat(section).split(" - ") if "Граница совместимости" in l), "")
        for needle in ("`version: 1`", "1.2.0", "`version: 2`", "двух ревью", "Fable", "metadata"):
            self.assertIn(needle, boundary)

    def test_fixtures_carry_no_home_paths_or_host_names(self):
        # Home paths are matched as written (`/users/` of a GitHub API URL is not one); the login
        # and the host names of the machines fixtures are captured on, in any letter case.
        paths = ("/home/", "/Users/")
        names = ("azureuser", "mh-central", "imac-mini", "macbook")
        found = []
        for path in sorted((ROOT / "tests" / "fixtures").rglob("*")):
            if not path.is_file():
                continue
            text = path.read_bytes().decode("utf-8", errors="replace")
            found += [f"{path.relative_to(ROOT)}: {word}" for word in paths if word in text]
            found += [f"{path.relative_to(ROOT)}: {word}" for word in names if word in text.lower()]
        self.assertEqual(found, [])

    def test_pr_body_template_reports_the_opus_fallback_and_the_fable_quota(self):
        text = doc("references/pr-review.md")
        template = next((b for b in fenced_blocks(text) if "Принятые ограничения" in b), None)
        self.assertIsNotNone(template, "pr-review.md has no PR body template with «Принятые ограничения»")
        line = next((l for l in template.splitlines() if "codex-host-opus" in l), "")
        self.assertIn("Запасное Opus-ревью", line)
        self.assertRegex(line, r"квот\w+ Fable")

    def test_brief_template_takes_the_model_from_state_and_high_review_runs_both_profiles(self):
        profiles = doc("references/profiles.md")
        template = next((b for b in fenced_blocks(profiles) if re.search(r'state\.py"? role-model', b)), None)
        self.assertIsNotNone(template, "profiles.md has no brief template with state.py role-model")
        self.assertIn("--role <coder|tester>", template)
        self.assertIn("claude-fable-5-1", template)
        contract = doc("references/review-contract.md")
        command = next((b for b in fenced_blocks(contract)
                        if len(re.findall(r'review\.py"? run', b)) == 2 and "--profile claude-host" in b), None)
        self.assertIsNotNone(command, "review-contract.md has no high-risk review command")
        self.assertRegex(command, r"--profile codex-host(?!-)")
        self.assertNotIn("codex-host-opus", command)
        self.assertEqual(len(set(re.findall(r"--packet (\S+)", command))), 1, "both runs take one packet")

    def test_docs_describe_the_risk_policy_second_reviewer_and_opus_fallback(self):
        for relative in ("references/profiles.md", "SKILL.md", "references/review-contract.md"):
            text = doc(relative)
            for needle in ("claude-fable-5-1", "claude-sonnet-5-5", "--model", "second_reviewer",
                           "codex-host-opus", "--quota-evidence"):
                with self.subTest(doc=relative, needle=needle):
                    self.assertIn(needle, text)
            with self.subTest(doc=relative, needle="risk"):
                self.assertRegex(flat(text), r"риск\w* high")
        for relative in ("references/profiles.md", "references/waves.md"):
            with self.subTest(doc=relative):
                self.assertIn(self.RULE, flat(doc(relative)).lower())
        workflow = doc("references/workflow.md")
        for needle in ("review_policy", "task-risk", "role-model", "--model", "second_reviewer",
                       "--quota-evidence", "unavailable"):
            with self.subTest(doc="references/workflow.md", needle=needle):
                self.assertIn(needle, workflow)


class ReleaseWaveGateDocs(unittest.TestCase):
    """1.2.2 (W2, #86): the merge gate by the risk of the wave, the coordinator's model, the two reviews of
    the plan checked by `launch`, the skill updated only between waves."""

    def test_release_1_2_2_is_versioned_and_names_the_compatibility_boundaries(self):
        changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
        sections = re.split(r"(?m)^## ", changelog)
        section = next((s for s in sections if s.startswith("1.2.2 — 2026-10-05")), None)
        self.assertIsNotNone(section, "CHANGELOG has no section 1.2.2")
        for issue in ("#86", "#91", "#92"):
            self.assertIn(issue, section)
        boundaries = [l for l in flat(section).split(" - ") if "Граница совместимости" in l]
        self.assertGreaterEqual(len(boundaries), 3, "each change of a default is its own boundary line")
        joined = " ".join(boundaries)
        for needle in ("`model`", "предупрежд", "`launch`", "ревью плана", "`plan_sha256`", "high-волн",
                       "`version: 1`", "новый прогон волны", "watch"):
            with self.subTest(needle=needle):
                self.assertIn(needle, joined)
        self.assertIn("только между волнами", flat(section))

    def test_waves_doc_describes_the_gate_by_the_risk_of_the_wave(self):
        text = doc("references/waves.md")
        gate = flat(text.split("### Гейт мерджа: `merge_gate: auto`", 1)[1].split("\n### ", 1)[0])
        for needle in ("Риск волны", "`<run_dir>/waves.json`", "`plan_sha256`", "каждая задача", "`second_reviewer`",
                       "`version: 1`", "новый прогон волны", "`review_policy.level`", "`review_history`",
                       "не верит сохранённому", "закрытый отказ",
                       # fix round 1: the highest known risk, the traces of the high policy, the honest border
                       "`wave.risk`", "наибольший", "`plan.wave_sha256`", "Записи политики high",
                       "Известная граница", "manifest не подписан"):
            with self.subTest(needle=needle):
                self.assertIn(needle, gate)

    def test_waves_doc_describes_the_coordinator_model_and_the_plan_review(self):
        text = doc("references/waves.md")
        whole = flat(text)
        phase_a = flat(text.split("## Фаза A — текущая сессия", 1)[1].split("### Схема `waves.json` v1", 1)[0])
        checklist = flat(text.split("### Предполётный чек-лист", 1)[1].split("### Мандат", 1)[0])
        mandate = flat(text.split("### Мандат", 1)[1].split("### Политика решений", 1)[0])
        fields = text.split("Поля `chain.json`:", 1)[1].split("**Admission.**", 1)[0]
        model_row = next((l for l in fields.splitlines() if l.startswith("| `model`")), "")
        self.assertIn("claude-fable-5-1", model_row)
        self.assertIn("предупрежд", model_row)
        self.assertIn('"model": "claude-fable-5-1"', text)
        self.assertIn("модель координатора", checklist)
        # the plan review: both reviewers, kept in the run directory, checked by launch
        for part, name in ((phase_a, "phase A"), (checklist, "checklist")):
            for needle in ("claude-host", "codex-host", "plan-review/"):
                with self.subTest(part=name, needle=needle):
                    self.assertIn(needle, part)
        for needle in ("`plan.sha256`", "`packet.json`", "`result-claude-host.json`", "`result-codex-host.json`",
                       "`result-codex-host-opus.json`", "`state_packet_hash`", "`wab.py launch`", "прошлых кругов",
                       "`sha256sum waves.json`", "не симлинк"):
            with self.subTest(needle=needle):
                self.assertIn(needle, whole)
        # the installed skill is updated only between waves
        for part, name in ((checklist, "checklist"), (mandate, "mandate")):
            with self.subTest(part=name):
                self.assertIn("только между волнами", part)
        table = text.split("## Что реализовано", 1)[1].split("## Фаза A", 1)[0]
        row = next((l for l in table.splitlines() if "1.2.2; #86" in l), "")
        for needle in ("риск", "plan-review", "`model`"):
            with self.subTest(row=needle):
                self.assertIn(needle, row)

    def test_workflow_and_protocol_no_longer_promise_the_gate_for_later(self):
        workflow = flat(doc("references/workflow.md"))
        self.assertNotIn("собственная проверка двух ревью в гейте — следующая волна", workflow)
        self.assertIn("по риску волны", workflow)
        self.assertNotIn("Требование двух ревью в гейте мерджа диспетчера — следующая волна",
                         flat(doc("references/waves.md")))
        protocol = flat(doc("scripts/waves/PROTOCOL.md"))
        self.assertIn("риск волны", protocol)
        self.assertIn("новый прогон", protocol)

    def test_opus_fallback_is_marked_as_not_proven_by_a_live_quota_event(self):
        for relative in ("references/profiles.md", "references/review-contract.md"):
            with self.subTest(doc=relative):
                text = flat(doc(relative))
                self.assertIn("#91", text)
                self.assertIn("не проверен живым событием квоты", text)


class ReleaseFableRolesDocs(unittest.TestCase):
    """1.2.3 (W3, #86 п.5-10): the Fable subagent roles of the ordinary pipeline and their briefs."""

    # role id -> how the docs name it (a stem: the word is declined in the text)
    ROLES = {
        "architect": "архитектор",
        "internal_reviewer": "внутренн",
        "triage": "триаж",
        "investigator": "следовател",
        "final_check": "финальн",
    }
    RULE = "обязательны в применимых случаях"
    MODEL_COMMANDS = ("`/model`", "`claude --model claude-fable-5-1`")

    def test_release_1_2_3_is_versioned_and_names_the_accepted_limitation(self):
        self.assertRegex(doc("SKILL.md"), r'(?m)^  version: "?1\.2\.3"?$')
        changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
        sections = re.split(r"(?m)^## ", changelog)
        section = next((s for s in sections if s.startswith("1.2.3 — 2026-10-05")), None)
        self.assertIsNotNone(section, "CHANGELOG has no section 1.2.3")
        self.assertEqual(sections.index(section), 1, "1.2.3 must be the newest section")
        self.assertTrue(sections[2].startswith("1.2.2 — "), "1.2.2 follows 1.2.3")
        self.assertIn("#86", section)
        items = flat(section).split(" - ")
        limitation = next((l for l in items if "Принятое ограничение" in l), "")
        for needle in ("архитектор", "триаж", "следовател", "машинно не проверяются", "`internal_reviewer`",
                       "`final_check`", "1.2.4"):
            with self.subTest(limitation=needle):
                self.assertIn(needle, limitation)
        boundary = next((l for l in items if "Граница совместимости" in l), "")
        for needle in ("`version: 1`", "`version: 2`", "1.2.2", "без новых полей"):
            with self.subTest(boundary=needle):
                self.assertIn(needle, boundary)
        fixed = section.split("### Исправлено", 1)[-1]
        for needle in ("Is a directory", "`wave.risk`"):
            with self.subTest(fixed=needle):
                self.assertIn(needle, fixed)

    def test_skill_and_workflow_name_the_roles_their_model_and_the_applicability_rule(self):
        for relative in ("SKILL.md", "references/workflow.md"):
            text = doc(relative)
            whole = flat(text)
            for role, word in self.ROLES.items():
                with self.subTest(doc=relative, role=role):
                    self.assertIn(f"`{role}`", whole)
                    self.assertIn(word, whole.lower())
                    # the model stands next to the role: one paragraph names both
                    paragraphs = [flat(part) for part in re.split(r"\n(?=\s*(?:[-*]|\d+\.) |\s*\n)", text)]
                    self.assertTrue(any(f"`{role}`" in part and "Fable" in part for part in paragraphs),
                                    f"{relative}: no paragraph names `{role}` together with Fable")
            with self.subTest(doc=relative, rule=self.RULE):
                self.assertIn(self.RULE, whole)
                sentence = next(part for part in re.split(r"(?<=[.;:]) ", whole) if self.RULE in part)
                self.assertNotIn("рекоменд", sentence.lower())
            self.assertIn("role-briefs.md", text)
        workflow = flat(doc("references/workflow.md"))
        rule = workflow.split(self.RULE, 1)[1][:900]
        for needle in ("архитектор", "шаге 1", "high", "триаж", "находках внешнего ревью", "следователь",
                       "баг", "внутреннее ревью", "финальная сверка", "отклонение", "причин"):
            with self.subTest(rule=needle):
                self.assertIn(needle, rule)
        for needle in ("машинно не проверяются", "W4", "1.2.4",
                       "task-result --role <роль> --status unavailable --model fable", "поле `model`",
                       "--source internal_reviewer", "`internal_rounds`", "`external_review`",
                       "requires manifest version 2"):
            with self.subTest(workflow=needle):
                self.assertIn(needle, workflow)

    def test_every_role_brief_carries_the_model_and_the_way_to_record_the_result(self):
        text = doc("references/role-briefs.md")
        blocks = fenced_blocks(text)
        for role in self.ROLES:
            brief = next((b for b in blocks if re.search(rf"(?m)^Роль: {role}\b", b)), None)
            with self.subTest(role=role):
                self.assertIsNotNone(brief, f"role-briefs.md has no brief of {role}")
                self.assertRegex(brief, r"(?m)^model: fable$")
                for needle in ("Вход:", "Выход:", "Запреты:", "Fable недоступна"):
                    self.assertIn(needle, brief)
                command = flat(brief.replace("\\\n", " "))
                self.assertRegex(command, rf"task-result [^\n]*--role {role} [^\n]*--model fable")
                self.assertIn(f"task-result --role {role} --status unavailable --model fable", command)
        for relative in ("SKILL.md", "references/profiles.md"):
            with self.subTest(link=relative):
                self.assertIn("(references/role-briefs.md)" if relative == "SKILL.md" else "(role-briefs.md)",
                              doc(relative))
        profiles = flat(doc("references/profiles.md"))
        for role in self.ROLES:
            with self.subTest(profiles=role):
                self.assertIn(f"`{role}`", profiles)

    def test_session_model_warning_for_high_risk_is_one_line_with_the_command(self):
        for relative, extra in (("SKILL.md", ()), ("references/waves.md", ("chain.json",))):
            lines = [l for l in doc(relative).splitlines() if all(c in l for c in self.MODEL_COMMANDS)]
            with self.subTest(doc=relative):
                self.assertEqual(len(lines), 1, f"{relative}: the warning must be exactly one line")
                for needle in ("high", "Fable", "не переключа", *extra):
                    self.assertIn(needle, lines[0])
        self.assertIn("координатор", next(l for l in doc("SKILL.md").splitlines()
                                          if all(c in l for c in self.MODEL_COMMANDS)).lower())

    def test_waves_doc_has_the_1_2_3_row_and_the_extended_gate_border(self):
        text = doc("references/waves.md")
        table = text.split("## Что реализовано", 1)[1].split("## Фаза A", 1)[0]
        row = next((l for l in table.splitlines() if "1.2.3; #86" in l), "")
        for needle in ("`architect`", "`internal_reviewer`", "`triage`", "`investigator`", "`final_check`",
                       "--source internal_reviewer"):
            with self.subTest(row=needle):
                self.assertIn(needle, row)
        gate = flat(text.split("### Гейт мерджа: `merge_gate: auto`", 1)[1].split("\n### ", 1)[0])
        border = gate.split("Известная граница: manifest не подписан", 1)[1]
        for needle in ("согласованно вычищен", "след", "одним ревью", "под пином", "`version: 2`"):
            with self.subTest(border=needle):
                self.assertIn(needle, border)


if __name__ == "__main__":
    unittest.main()
