#!/usr/bin/env python3
"""Acceptance checks for the installable standalone skill layout."""

import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SKILL = ROOT / "skills" / "superarmanda"
EXPECTED_FILES = {
    "SKILL.md",
    "references/profiles.md",
    "references/workflow.md",
    "references/review-contract.md",
    "references/pr-review.md",
    "schemas/review-result.schema.json",
    "scripts/state.py",
    "scripts/review.py",
    "scripts/codex_review.py",
    "scripts/pr_review.py",
}


def source_files(skill):
    """List source files, excluding only CPython's generated bytecode cache."""
    files = set()
    for path in skill.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(skill)
        if relative.parent.name == "__pycache__" and path.suffix == ".pyc":
            continue
        files.add(relative.as_posix())
    return files


def assert_package_layout(skill):
    if source_files(skill) != EXPECTED_FILES:
        raise AssertionError(source_files(skill) ^ EXPECTED_FILES)


class StandaloneLayoutTest(unittest.TestCase):
    def test_skill_is_installable_from_the_canonical_skill_directory(self):
        assert_package_layout(SKILL)

    def test_rejects_missing_or_extra_source_files_but_allows_generated_bytecode(self):
        with tempfile.TemporaryDirectory() as directory:
            skill = Path(directory)
            for relative in EXPECTED_FILES:
                path = skill / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                path.touch()
            (skill / "scripts/__pycache__").mkdir()
            (skill / "scripts/__pycache__/state.cpython-312.pyc").touch()
            assert_package_layout(skill)

            (skill / "scripts/unexpected.py").touch()
            with self.assertRaises(AssertionError):
                assert_package_layout(skill)
            (skill / "scripts/unexpected.py").unlink()

            (skill / "scripts/state.py").unlink()
            with self.assertRaises(AssertionError):
                assert_package_layout(skill)


if __name__ == "__main__":
    unittest.main()
